FROM ubuntu:20.04

RUN apt-get update && apt-get upgrade -y

RUN apt-get install sudo -y && apt-get install wget -y && apt-get install gnupg -y

RUN echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main" | tee -a /etc/apt/sources.list
RUN wget -O llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key && \
    sudo apt-key add llvm-snapshot.gpg.key && \
    rm llvm-snapshot.gpg.key

RUN apt-get update

RUN apt-get install make -y && apt-get install cmake -y && apt-get install ccache -y && apt-get install git -y && apt-get install clang-13 -y

RUN apt-get install libstdc++-10-dev -y && apt-get install libx11-dev -y && apt-get install zlib1g-dev -y
RUN apt-get install libcurl4-openssl-dev -y && apt-get install libgmp-dev -y

RUN apt-get install texinfo -y && apt-get install pkg-config -y && apt-get install m4 -y

RUN adduser fibos -q && chmod 777 /root
